### PR TITLE
API Doc Updates, contd.

### PR DESCRIPTION
**Pull request by shyam-habarakada**
This PR includes,

* Make the landing README page more concise and easy to use by highlighting the various sections and moving verbose sections to their own pages
* Minor updates to the end points section 
* Start calling out read-only attributes
* Corrections from proofreading

View this version of the docs via https://github.com/10Kft/10kft-api/tree/v1-overhaul

### CODE REVIEW

**Comment by shyam-habarakada** [comment]
@10Kft/10kft-team this PR attempts to address some of the issues that were highlighted in an internal slack discussion about the API documentation. Specifically, the one about the initial entry point not immediately pointing to the various API endpoints that are available (they were below the fold / further down on the page, which some readers were not immediately discovering them).

**Comment by swordfish444** [comment]
@shyam-habarakada I believe @thenickcox may have already started working on moving the docs to the _Github Wiki_ section. You can find the trello card documenting this work [here](https://trello.com/c/ayFMgh68/1337-api-reformat-api-docs-to-fit-wiki-style-nav-structure-a-la-baucis).

**Comment by shyam-habarakada** [comment]
[[API] Reformat API docs to fit Wiki-style nav structure à la Baucis](https://trello.com/c/ayFMgh68/1337-api-reformat-api-docs-to-fit-wiki-style-nav-structure-a-la-baucis)

**Comment by swordfish444** [comment]
@shyam-habarakada In our old api docs we had two sections for _time entries_; user and project. 

I'm only seeing a single section which covers time entries by user. Personally, I've referred to both time entry pages a number of times solving tickets and/or investigating bugs and I would like to recommend we include the missing section 🙏 🙏

**Comment by shyam-habarakada** [comment]
@swordfish444 updated the time entries API docs to address your feedback https://github.com/10Kft/10kft-api/blob/v1-overhaul/sections/time-entries.md

**Comment by shyam-habarakada** [comment]
@10Kft/10kft-team merging this so I can use the latest in a discussion with a customer.

**Pull request merged**
